In [ ]:
def refresh_repo():
    %cd /kaggle/working
    %rm -rf hotflip
    !git clone https://github.com/jefri021/hotflip.git
    %cd /kaggle/working/hotflip/
    !git pull origin main

refresh_repo()

/kaggle/working
Cloning into 'hotflip'...
remote: Enumerating objects: 57, done.
remote: Counting objects: 100% (57/57), done.
remote: Compressing objects: 100% (26/26), done.
remote: Total 57 (delta 15), reused 56 (delta 14), pack-reused 0 (from 0)
Receiving objects: 100% (57/57), 2.46 MiB | 9.68 MiB/s, done.
Resolving deltas: 100% (15/15), done.
/kaggle/working/hotflip
From https://github.com/jefri021/hotflip
 * branch            main       -> FETCH_HEAD
Already up to date.


In [ ]:
from torch.utils.data import TensorDataset, DataLoader

return DataLoader(
        edited_samples,
        batch_size=bs,
        shuffle=False,
        pin_memory=pin,
        num_workers=nw,
        persistent_workers=pers if nw > 0 else False,
        collate_fn=_collate_varlen,
    )

In [ ]:
import torch

# Path to your .pt file
file_path = "/kaggle/working/hotflip/rounds/round_000_samples.pt"

# Load the tensor / model / checkpoint
data = torch.load(file_path, map_location='cpu')  # or 'cuda' if on GPU

print(type(data))
for d in data:
    print(d)
    input()

<class 'list'>
(tensor([    2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
            2,     2,     2,     2,     2,     2,     2,     2,     1,  1724,
          947, 25167, 21958,  1827,  1048,  5360, 29973]), tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
        1, 1, 1]))
(tensor([    2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
            2,     2,     2,     2,     2,     2,     2,     2,     1,  1724,
          947,  9582, 21958,  1827,  1048,  5360, 29973]), tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
        1, 1, 1]))
(tensor([    2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
            2,     2,     2,     2,     2,     2,     2,     2,     1,  1724,
          947,  3908, 21958,  1827,  1048,  5360, 29973]), tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
        1, 1, 1]))


(tensor([    2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
            2,     2,     2,     2,     2,     2,     2,     2,     1,  1724,
          947, 30444, 21958,  1827,  1048,  5360, 29973]), tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
        1, 1, 1]))


KeyboardInterrupt: Interrupted by user